**#To know how many fuctions include numpy**


In [1]:
import numpy
dir(numpy)
#OR
#numpy.press tab

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [1]:
import numpy
a=numpy.array([2,2,24,5,2,5])
print(a)

[ 2  2 24  5  2  5]


# linespace()


In [1]:
import numpy
a=numpy.linspace(1,2,num=100,dtype=int,endpoint=True)
print(a)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2]


In [19]:
import numpy
#Takes num=50 by-default and generate Random Numbers
a=numpy.linspace(2,100,num=50,dtype=int,endpoint=False)
print(a)

[ 2  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


# logspace()

In [8]:
import numpy
# (start,end,num,base) 2^1 to 2^10 generate 5 Numbers (base by default 10)
a=numpy.logspace(1,10,5,base=2,dtype=int,endpoint=True)
print(a)

[2 2 2 3 4]


# arange()

In [7]:
import numpy
#Odd Numbers range
a=numpy.arange(1,100,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [42]:
import numpy
#arange 
#Even Numbers range(start,end(n+1),datatype)
a=numpy.arange(1,101,2,dtype=int)
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# zeros()

In [47]:
import numpy
#zeros()
a=numpy.zeros(100,dtype=int)
print(a)
print(len(a))


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
100


# ones()

In [3]:
import numpy
#ones(range,dtype(by-default  float)) 
a=numpy.ones(10,dtype=int)
print(a)
print(len(a))


[1 1 1 1 1 1 1 1 1 1]
10


## Element to Element Addition of Array

In [56]:
import numpy
a=numpy.arange(1,11,dtype=int)
b=numpy.arange(1,11,dtype=int)
print(a+b)


[ 2  4  6  8 10 12 14 16 18 20]


# any()

In [70]:
# it check all elements in array and if any one is True its return True othr. False
import numpy
a=numpy.arange(1,11,dtype=int)
b=numpy.arange(1,11,dtype=int)
c=a==b
any(c)
print(c)

[ True  True  True  True  True  True  True  True  True  True]


# all()

In [71]:
# it check all elememts in array and if  all True then it return True othr. False
import numpy
a=numpy.array([1,2,4,5,6])
b=numpy.array([1,2,3,5,6])
c=a==b
any(c)
print(c)



[ True  True False  True  True]


In [73]:
#all() it check all elememts in array and if  all True then it return True othr. False
import numpy
a=numpy.array([1,2,4,5,6])
b=numpy.array([2,3,3,7,6])
print(any(a==b))



True


In [75]:
#all() it check all elememts in array and if  all True then it return True othr. False
import numpy
a=numpy.array([1,2,4,5,6])
b=numpy.array([1,3,4,5,6])
c=a==b
all(c)
print(c)



[ True False  True  True  True]


In [1]:

print("Chetan")

Chetan


## Prime numbers in the given by user

In [6]:
n=int(input("Enter the range"))
for i in range(2,n):
    c=2
    while(i%c!=0):
        c+=1
        
    if(i==c):
        print(i)

Enter the range10
2
3
5
7
